//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidWebAPI.Base
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class Questionnnare
    {
        public int ID { get; set; }
        public int PatientID { get; set; }
        public Nullable<bool> IsBeenInPlaces { get; set; }
        public Nullable<bool> IsBeenContactedInPlaces { get; set; }
        public Nullable<bool> IsBeenContacted { get; set; }
        public Nullable<bool> IsWorking { get; set; }
        public Nullable<bool> IsSick { get; set; }
        public Nullable<bool> IsCovidBefore { get; set; }
        public Nullable<bool> IsSickNow { get; set; }

        [JsonIgnore]
        public virtual Patient Patient { get; set; }
    }
}
