//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidWebAPI.Base
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class Review
    {
        public long ID { get; set; }
        public int VaccinationPointID { get; set; }
        public int PatientID { get; set; }
        public byte Rating { get; set; }
        public string Text { get; set; }

        public int? RatingInt => Convert.ToInt32(Rating);

        [JsonIgnore]
        public virtual Patient Patient { get; set; }
        [JsonIgnore]
        public virtual VaccinationPoint VaccinationPoint { get; set; }
    }
}
